Repository CCSU-Computer-Science-Club/CS-Club-Discord-Server-Bots, pull requests merged in 2023-11, with the labels that each got.

#8 Created a Class PalmAI with some starter code.
  Common/PalmAi.py
  InterviewPrepBot/Interview_prep_bot.py
  InterviewPrepBot/PalmAi.py
Labels: enhancement

#5 Implements basic coding challenge bot
  .gitignore
  CodingChallengerBot/.env.example
  CodingChallengerBot/DockerFiles/buildDocker.bat
  CodingChallengerBot/DockerFiles/buildDocker.sh
  CodingChallengerBot/DockerFiles/javascript.dockerfile
  CodingChallengerBot/DockerFiles/python.dockerfile
  CodingChallengerBot/DockerFiles/test.js
  CodingChallengerBot/DockerFiles/test.ts
  CodingChallengerBot/DockerFiles/typescript-entry.sh
  CodingChallengerBot/DockerFiles/typescript.dockerfile
  CodingChallengerBot/README.md
  CodingChallengerBot/bot.py
  CodingChallengerBot/clean-database.py
  CodingChallengerBot/codeValidator.py
  CodingChallengerBot/requirements.txt
  CodingChallengerBot/scrapeChallenges.py
  CodingChallengerBot/scrape_stage2/index.ts
  CodingChallengerBot/scrape_stage2/package-lock.json
  CodingChallengerBot/scrape_stage2/package.json
  CodingChallengerBot/test.py
Labels: enhancement

#11 palmAi class
  Common/PalmClient.py
  InterviewPrepBot/Interview_prep_bot.py
Labels: enhancement

#13 migrate coding challenge bot to CSBotCommon
  CodingChallengerBot/bot.py
Labels: enhancement

#14 Fix common bot class
  CSBotCommon/CSBotCommon/__init__.py
  Common/PalmClient.py
Labels: bug

#12 7 create a class palm api client in the common folder
  CSBotCommon/CSBotCommon/__init__.py
  InterviewPrepBot/career_coach.py
  example_bot.py
Labels: enhancement

#15 output_max_length is now optional
  CSBotCommon/CSBotCommon/__init__.py
  InterviewPrepBot/career_coach.py
Labels: enhancement

#17 Code runner restructuring
  .env.example
  .gitignore
  CodeRunnerService/codeRunnerApi.py
  CodeRunnerService/codeValidatorService.py
  CodingChallengerBot/bot.py
  ServiceManager/serviceManager.py
Labels: enhancement

#19 point bot.py to new code runner api
  CodingChallengerBot/bot.py
Labels: bug

#20 Service documentation
  CSBotCommon/README.md
  CodeRunnerService/README.md
  CodeRunnerService/codeRunnerApi.py
  CodeRunnerService/codeValidatorService.py
  CodingChallengerBot/README.md
  CodingChallengerBot/bot.py
  README.md
Labels: documentation

#21 Minor consistency change
  CodingChallengerBot/bot.py
Labels: bug

#24 18 profanity check on user input and ai ouptut
  .idea/.gitignore
  CSBotCommon/CSBotCommon/__init__.py
  InterviewPrepBot/Profanity_Checker.py
  InterviewPrepBot/career_coach.py
  InterviewPrepBot/profanity_dataset.json
  InterviewPrepBot/profanityen.csv
  requirements.txt
Labels: enhancement

#26 Execution Hardening
  .gitignore
  CodeRunnerService/codeValidatorService.py
  CodingChallengerBot/bot.py
  CodingChallengerBot/scrape_stage1/scrapeChallenges.py
  CodingChallengerBot/utility/clean-database.py
  README.md
  ServiceManager/serviceManager.py
  service.json
Labels: enhancement
